---
server:
  context-path: /api/

spring:
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Using Docker Instance
  datasource:
    url: jdbc:mysql://192.168.99.100:32768/flow-simulator?useSSL=false
    username: root
    password: root



