---
server:
  context-path: /api/

spring:
    jpa:
        show-sql: true

security:
    user:
        entityName: user
        password: password

max:
    page:
        size:
            limit: 100

page:
    start:
        default: 0
