---
server:
  context-path: /api/

spring:
  jpa:
    show-sql: true

  # Using Docker Instance
  datasource:
    url: jdbc:mysql://192.168.99.100:32768/flow-simulator?useSSL=false

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    username: root
    password: root
    driver-class-entityName: com.mysql.jdbc.Driver

