spring:
    jpa:
        show-sql: false

spring:
    datasource:
        url: jdbc:mysql://192.168.99.100:32768/flow-simulator?useSSL=false
        username: root
        password: root

security:
    user:
        entityName: user
        password: password

max:
    page:
        size:
            limit: 100

page:
    start:
        default: 0
